### PR TITLE
update dev-dependencies

### PR DESCRIPTION
**Pull request by jeetiss**

### CODE REVIEW

**Comment by Andarist** [comment]
Because of jsdom changes you have to change test script by specifying node as its env, like here:
https://github.com/Andarist/callbag-timer/blob/869a1b2139c9999fe69655b411eb7da1a105d37c/package.json#L12

**Comment by jeetiss** [comment]
@Andarist, wow
it works now 🙌🏻

**Comment by jeetiss** [comment]
@Andarist it's works, finally

**Comment by Andarist** [comment]
Thanks! Out of curiosity, are you planning on refactoring the code to fix your issue? I was planning to do it this week, but ofc I'm happy to accept contributions :)

**Comment by jeetiss** [comment]
I'm planning doing some stuff for testing callbags, and after it maybe i can fix that issue

**Pull request merged**
